version: 2
jobs:
  build:
    working_directory: ~/estimeo-highlights-sample2/
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hello world"
      - run: sudo npm install -g npm@latest
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run start
      - deploy:
                name: Deploy Master to Heroku
                command: |
                  if [ "${CIRCLE_BRANCH}" == "master" ]; then
                    git push heroku master
                    heroku logs --tail
                    heroku npm run start deploy
                    heroku logs --tail
                    heroku restart
                  fi